setup-dev-environment.md: - Corrected the signup process for codio account and DuckDuckGo on codio
duckduckgo/duckduckhack-docs pull request #114
Opened 2016-12-05 08:18 UTC by vigzmv

Fixes #113 

setup-dev-environment.md: - Corrected the signup process for codio account and DuckDuckGo on codio

2016-12-05 11:28 UTC, tagawa requested changes

2016-12-05 11:28 UTC, tagawa commented on welcome/setup-dev-environment.md
> +### 2a. Sign Up for a Account and Join the DuckDuckGo Organization on Codio
Please change `a Account` to `an Account`

2016-12-05 11:28 UTC, tagawa commented on welcome/setup-dev-environment.md
> +2. Click the green "**GitHub**" icon.
There are two "step 2" here - this line should be step 3, etc.

2016-12-05 11:28 UTC, tagawa commented on welcome/setup-dev-environment.md
> +7. You should see a confirmation message at the bottom of your Codio screen after clicking.
I couldn't see a confirmation message (I probably just missed it) so maybe we can change step 7 to:
`7. You can check that it worked by looking for DuckDuckGo in the organization list in your [Codio settings page](https://codio.com/home/settings/).`

2016-12-05 11:29 UTC, tagawa commented
Well spotted @vigzmv! I hadn't realised it had become easier to join Codio, so this is good news for all new contributors. Thank you for updating the instructions - I just made a few comments.

2016-12-05 13:29 UTC, vigzmv commented
setup-dev-environment.md - Requested changes applied :)

2016-12-05 22:25 UTC, moollaza commented
@vigzmv thanks for the updates! This LGTM :+1:

2016-12-05 22:25 UTC, merged

2018-09-19 14:47 UTC, csetarun commented
Unable to login with the invitation code provided. It is expired.